name: Generate Sponsors README
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Generate Sponsors 💖
        uses: JamesIves/github-sponsors-readme-action@1.0.5
        with:
          token: ${{ secrets.SPONSORS_NTSENG }}
          file: 'README.md'

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: main
          folder: '.'

      - name: Update Commands
        run: node .github/workflows/updateCommands.js

      - name: upload to wiki
        uses: OrlovM/Wiki-Action@v1
        with:
          path: 'Wiki'
          token: ${{ secrets.SPONSORS_NTSENG }}
